Projeler: Senin listenden 7 tane:

Yapay Sinir Ağları ile Görüntü Sınıflandırma (MLP) -yapmıştım tekrar yapmicam

CNN ile Rakam Görüntüsü Sınıflandırma (MNIST) -yapmıştım tekrar yapmicam

LSTM ile Film Yorumları Duygu Analizi

GAN ile Görüntü Oluşturma

Transformers ile Duygu Analizi (Text)

Autoencoder ile Moda Görüntüleri (Fashion-MNIST)

Transfer Learning ile İlaç Görüntüleri Sınıflandırma

**Transformers ile Duygu Analizi (Text)**

In [3]:
!pip install transformers datasets torch -q  # transformers (BERT vb.), datasets (hazır veri setleri), torch (deep learning kütüphanesi) yüklenir, -q sessiz kurulum yapar

import torch  # PyTorch kütüphanesi; tensor işlemleri ve model eğitimi için kullanılır
from datasets import load_dataset  # HuggingFace datasets kütüphanesinden veri seti yüklemek için kullanılır
from transformers import AutoTokenizer  # Metni sayısal hale getiren tokenizer'ı otomatik seçmek için kullanılır
from transformers import AutoModelForSequenceClassification  # Hazır eğitilmiş sınıflandırma modeli (BERT vb.) yüklemek için kullanılır
from transformers import TrainingArguments, Trainer  # Model eğitimini kolaylaştıran hazır eğitim araçları

In [4]:
dataset = load_dataset("imdb")  # HuggingFace üzerinden IMDb film yorumları veri setini indirir ve dataset değişkenine atar

print(dataset)  # Dataset'in genel yapısını (train/test bölümleri, veri sayıları) ekrana yazdırır

print(dataset["train"][0])  # Eğitim verisindeki ilk örneği gösterir (text + label)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})
{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}

In [5]:
for i in range(5):  # 0'dan 4'e kadar ilk 5 veriyi döner
    print(dataset["train"][i])  # her bir veriyi ekrana yazdırır
    print("------")  # verileri ayırmak için çizgi koyar

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}
------
{'text': '"I Am Curious: Yellow" is a risible and pretentious steaming pile. It doesn\'t matter what one\'s political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn\'t true. I\'ve seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don\'t exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we\'re treated to the site of Vincent Gallo\'s throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) "double-standard" in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference between men and women: there are no genitals on display when actresses appears nude, and the same cannot be said for a man. In fact, you generally won\'t see female genitals in an American film in anything short of porn or explicit erotica. This alleged double-standard is less a double standard than an admittedly depressing ability to come to terms culturally with the insides of women\'s bodies.', 'label': 0}
------
{'text': "If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story.<br /><br />One might feel virtuous for sitting thru it because it touches on so many IMPORTANT issues but it does so without any discernable motive. The viewer comes away with no new perspectives (unless one comes up with one while one's mind wanders, as it will invariably do during this pointless film).<br /><br />One might better spend one's time staring out a window at a tree growing.<br /><br />", 'label': 0}
------
{'text': "This film was probably inspired by Godard's Masculin, féminin and I urge you to see that film instead.<br /><br />The film has two strong elements and those are, (1) the realistic acting (2) the impressive, undeservedly good, photo. Apart from that, what strikes me most is the endless stream of silliness. Lena Nyman has to be most annoying actress in the world. She acts so stupid and with all the nudity in this film,...it's unattractive. Comparing to Godard's film, intellectuality has been replaced with stupidity. Without going too far on this subject, I would say that follows from the difference in ideals between the French and the Swedish society.<br /><br />A movie of its time, and place. 2/10.", 'label': 0}
------
{'text': 'Oh, brother...after hearing about this ridiculous film for umpteen years all I can think of is that old Peggy Lee song..<br /><br />"Is that all there is??" ...I was just an early teen when this smoked fish hit the U.S. I was too young to get in the theater (although I did manage to sneak into "Goodbye Columbus"). Then a screening at a local film museum beckoned - Finally I could see this film, except now I was as old as my parents were when they schlepped to see it!!<br /><br />The ONLY reason this film was not condemned to the anonymous sands of time was because of the obscenity case sparked by its U.S. release. MILLIONS of people flocked to this stinker, thinking they were going to see a sex film...Instead, they got lots of closeups of gnarly, repulsive Swedes, on-street interviews in bland shopping malls, asinie political pretension...and feeble who-cares simulated sex scenes with saggy, pale actors.<br /><br />Cultural icon, holy grail, historic artifact..whatever this thing was, shred it, burn it, then stuff the ashes in a lead box!<br /><br />Elite esthetes still scrape to find value in its boring pseudo revolutionary political spewings..But if it weren\'t for the censorship scandal, it would have been ignored, then forgotten.<br /><br />Instead, the "I Am Blank, Blank" rhythymed title was repeated endlessly for years as a titilation for porno films (I am Curious, Lavender - for gay films, I Am Curious, Black - for blaxploitation films, etc..) and every ten years or so the thing rises from the dead, to be viewed by a new generation of suckers who want to see that "naughty sex film" that "revolutionized the film industry"...<br /><br />Yeesh, avoid like the plague..Or if you MUST see it - rent the video and fast forward to the "dirty" parts, just to get it over with.<br /><br />', 'label': 0}
------

In [6]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")  # hazır BERT tokenizer'ını indirir (küçük harfli İngilizce model)

def tokenize_function(example):  # her veri örneği için çalışacak fonksiyonu tanımlar
    return tokenizer(
        example["text"],  # text alanını alır (film yorumu)
        padding="max_length",  # tüm verileri aynı uzunluğa getirir (eksik olanları doldurur)
        truncation=True,  # çok uzun metinleri keser (modelin kabul ettiği max uzunluğa indirir)
        max_length=256  # maksimum 256 token uzunluk belirler (çok uzunları keser)
    )

tokenized_datasets = dataset.map(tokenize_function, batched=True)  # tüm dataset'e tokenize işlemini uygular (batch halinde daha hızlı)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [7]:
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",  # hazır BERT modeli (küçük harfli İngilizce)
    num_labels=2  # sınıf sayısı (pozitif / negatif → 2 sınıf)
)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
training_args = TrainingArguments(
    output_dir="./results",  # model çıktılarının kaydedileceği klasör (checkpoint vs)
    eval_strategy="epoch",  # HER EPOCH sonunda modeli test et (evaluation_strategy yerine bu kullanılıyor)
    learning_rate=2e-5,  # öğrenme hızı → model ağırlıkları ne kadar değişsin
    per_device_train_batch_size=8,  # her adımda 8 veri ile öğrenir (RAM dengesi için düşük tutulur)
    per_device_eval_batch_size=8,  # test sırasında da 8 veri kullanılır
    num_train_epochs=2,  # tüm veriyi 2 kez görür (epoch sayısı)
    weight_decay=0.01,  # aşırı öğrenmeyi (overfitting) azaltır
)

In [9]:
trainer = Trainer(
    model=model,  # eğitilecek BERT modeli (duygu analizi için)
    args=training_args,  # biraz önce tanımladığımız eğitim ayarları
    train_dataset=tokenized_datasets["train"],  # modelin öğreneceği veri (25k yorum)
    eval_dataset=tokenized_datasets["test"],  # modelin test edileceği veri (25k yorum)
)

In [10]:
trainer.train()  # modeli eğitmeye başlatır (en önemli satır)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
trainer.evaluate()  # modelin test verisindeki performansını ölçer

In [ ]:
text = "This movie was absolutely amazing!"  # modelin yorumlayacağı yeni bir cümle

inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)  # metni modele uygun tensor formatına çevirir

outputs = model(**inputs)  # modeli çalıştırır ve tahmin üretir

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)  # çıktıyı olasılıklara çevirir

predicted_class = torch.argmax(predictions).item()  # en yüksek olasılığa sahip sınıfı seçer

print(predicted_class)  # sonucu yazdırır (0 negatif, 1 pozitif)

In [ ]:
from sklearn.metrics import accuracy_score  # modelin doğruluk oranını hesaplamak için gerekli fonksiyon

def compute_metrics(eval_pred):  # Trainer'ın evaluation sırasında çağıracağı fonksiyon
    logits, labels = eval_pred  # modelin çıktıları (logits) ve gerçek etiketler (labels) alınır
    predictions = logits.argmax(axis=-1)  # en yüksek skora sahip sınıf seçilir (0 veya 1)
    acc = accuracy_score(labels, predictions)  # gerçek ve tahmin karşılaştırılır → accuracy hesaplanır
    return {"accuracy": acc}  # Trainer'ın anlayacağı formatta sözlük döndürülür

In [ ]:
trainer = Trainer(
    model=model,  # eğitilecek model
    args=training_args,  # eğitim ayarları
    train_dataset=tokenized_datasets["train"],  # eğitim verisi
    eval_dataset=tokenized_datasets["test"],  # test verisi
    compute_metrics=compute_metrics,  # az önce yazdığımız accuracy fonksiyonunu ekler
)

In [ ]:
trainer.train()  # modeli eğitir

results = trainer.evaluate()  # test verisinde performansı ölçer

print(results)  # accuracy ve loss değerlerini ekrana yazdırır

In [ ]:
from sklearn.metrics import confusion_matrix  # confusion matrix hesaplamak için
import numpy as np  # array işlemleri için

predictions = trainer.predict(tokenized_datasets["test"])  # test verisi için tahmin yapar

preds = np.argmax(predictions.predictions, axis=-1)  # en yüksek olasılıklı sınıfı seçer
labels = predictions.label_ids  # gerçek etiketleri alır

cm = confusion_matrix(labels, preds)  # confusion matrix oluşturur

print(cm)  # matrisi yazdırır

In [11]:
import matplotlib.pyplot as plt  # grafik çizmek için

accuracy = results["eval_accuracy"]  # accuracy değerini alır

plt.bar(["Accuracy"], [accuracy])  # tek bar grafik oluşturur
plt.title("Model Accuracy")  # grafik başlığı
plt.show()  # grafiği ekranda gösterir

NameError: name 'results' is not defined